

/**
 * Dashboard drop downs
 */
export const SET_PROVISION_DROPDOWN = '@@provisionDropDown/SET_PROVISION_DROPDOWN'
export const SET_SYSTEM_DROPDOWN = '@@systemDropdown/SET_SYSTEM_DROPDOWN'
export const SET_METHOD_DROPDOWN = '@@methodDropdown/SET_METHOD_DROPDOWN'

/**
 * Sheets
 */
export const ADD_NEW_SHEET = '@@sheets/ADD_NEW_SHEET'
export const SET_TAB_STATE = '@@sheets/SET_TAB_STATE'
export const SET_SELECTED_SHEET = '@@sheets/SET_SELECTED_SHEET'

/**
 * Sheet Details
 */
export const SET_PROJECT_UNIT = '@@sheets/SET_PROJECT_UNIT'
export const SET_PROJECT_NAME = '@@sheets/SET_PROJECT_NAME'
export const SET_PROJECT_ID = '@@sheets/SET_PROJECT_ID'
export const SET_PROJECT_COMPANY = '@@sheets/SET_PROJECT_COMPANY'
export const SET_PROJECT_DESIGNER = '@@sheets/SET_PROJECT_DESIGNER'
export const SET_PROJECT_CLIENT = '@@sheets/SET_PROJECT_CLIENT'
export const SET_PROJECT_NOTES = '@@sheets/SET_PROJECT_NOTES'

/**
 * Sheet Factors
 */
export const SET_SAFETY_FACTOR_FOR_TENSILE = '@@sheets/SET_SAFETY_FACTOR_FOR_TENSILE'
export const SET_SAFETY_FACTOR_FOR_COMPRESSION = '@@sheets/SET_SAFETY_FACTOR_FOR_COMPRESSION'
export const SET_SAFETY_FACTOR_FOR_FLEXURE = '@@sheets/SET_SAFETY_FACTOR_FOR_FLEXURE'
export const SET_SAFETY_FACTOR_FOR_SHEAR = '@@sheets/SET_SAFETY_FACTOR_FOR_SHEAR'

/**
 * Sheet Forces
 */
export const SET_BENDING_MOMENT_ALONG_X_AXIS = '@@sheets/SET_BENDING_MOMENT_ALONG_X_AXIS'
export const SET_BENDING_MOMENT_ALONG_Y_AXIS = '@@sheets/SET_BENDING_MOMENT_ALONG_Y_AXIS'
export const SET_SHEAR_ALONG_X_AXIS = '@@sheets/SET_SHEAR_ALONG_X_AXIS'
export const SET_SHEAR_ALONG_Y_AXIS = '@@sheets/SET_SHEAR_ALONG_Y_AXIS'
export const SET_AXIAL = '@@sheets/SET_AXIAL'

/**
 * Sheet MemberFields
 */
export const SET_MEMBER_ID = '@@sheets/SET_MEMBER_ID'
export const SET_MATERIAL_ID = '@@sheets/SET_MATERIAL_ID'
export const SET_SECTION_ID = '@@sheets/SET_SECTION_ID'
export const SET_TOTAL_LENGTH_OF_MEMBER = '@@sheets/SET_TOTAL_LENGTH_OF_MEMBER'
export const SET_Y_AXIS_UNBRACED_LENGTH = '@@sheets/SET_Y_AXIS_UNBRACED_LENGTH'
export const SET_Y_AXIS_EFFECTIVE_LENGTH_FACTOR = '@@sheets/SET_Y_AXIS_EFFECTIVE_LENGTH_FACTOR'
export const SET_Z_AXIS_UNBRACED_LENGTH = '@@sheets/SET_Z_AXIS_UNBRACED_LENGTH'
export const SET_Z_AXIS_EFFECTIVE_LENGTH_FACTOR = '@@sheets/SET_Z_AXIS_EFFECTIVE_LENGTH_FACTOR'
export const SET_LLT = '@@sheets/SET_LLT'
export const SET_UNBRACED_LENGTH_LATERAL_TORSIONAL = '@@sheets/SET_UNBRACED_LENGTH_LATERAL_TORSIONAL'
export const SET_LATERAL_TORSIONAL_MODIFICATION_FACTOR = '@@sheets/SET_LATERAL_TORSIONAL_MODIFICATION_FACTOR'
export const SET_SLENDERNESS_RATIO_IN_COMPRESSION = '@@sheets/SET_SLENDERNESS_RATIO_IN_COMPRESSION'
export const SET_SLENDERNESS_RATIO_IN_TENSION = '@@sheets/SET_SLENDERNESS_RATIO_IN_TENSION'
export const SET_LST = '@@sheets/SET_LST'